name: 🐛 Bug Report
description: Report a bug or issue with Transparency
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the sections below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "The application crashes when..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: "I expected..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: "Instead, what happened was..."
    validations:
      required: true

  - type: dropdown
    id: platform-version
    attributes:
      label: Platform Version
      description: What version of Transparency are you using?
      options:
        - v2.1.0 (latest)
        - v2.0.0
        - v1.0.0
        - Development/unreleased
        - Unknown
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS (latest)
        - macOS (older version)
        - Windows 11
        - Windows 10
        - Linux (Ubuntu)
        - Linux (other)
        - Other
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "e.g., 3.11.0"
    validations:
      required: true

  - type: dropdown
    id: installation-method
    attributes:
      label: Installation Method
      description: How did you install the platform?
      options:
        - Downloaded DMG/installer
        - Built from source
        - Git clone + pip install
        - Other
    validations:
      required: true

  - type: checkboxes
    id: affected-features
    attributes:
      label: Affected Features
      description: Which features are affected by this bug?
      options:
        - label: FEC API searches
        - label: API key management
        - label: Application startup
        - label: Update checker
        - label: User interface
        - label: Data export
        - label: Configuration
        - label: Other

  - type: dropdown
    id: severity
    attributes:
      label: Bug Severity
      description: How severe is this bug?
      options:
        - Critical (application unusable)
        - High (major feature broken)
        - Medium (feature partially broken)
        - Low (minor issue)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log Output
      description: Please include relevant log entries from ~/.transparency/app.log
      placeholder: |
        [2024-01-01 12:00:00] ERROR: ...
        [2024-01-01 12:00:01] TRACEBACK: ...
      render: text

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: "Drag and drop screenshots here or paste image URLs"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: "This started happening after..."

  - type: checkboxes
    id: workaround
    attributes:
      label: Workaround
      description: Have you found any workarounds?
      options:
        - label: I have found a workaround (please describe in additional context)
        - label: No workaround found

  - type: checkboxes
    id: regression
    attributes:
      label: Regression
      description: Is this a regression from a previous version?
      options:
        - label: This worked in a previous version
        - label: This is a new issue
        - label: Unknown

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help fix this bug?
      options:
        - label: I would like to work on fixing this bug
        - label: I can help with testing the fix
        - label: I can provide additional information if needed 