name: Community Management

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]
  schedule:
    # Run daily at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  triage-issues:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened'
    steps:
      - name: Auto-label license inquiries
        if: contains(github.event.issue.title, '[LICENSE]')
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['license', 'business', 'needs-review']
            });

      - name: Auto-label feature requests
        if: contains(github.event.issue.title, '[FEATURE]')
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['enhancement', 'community-request']
            });

      - name: Auto-label bug reports
        if: contains(github.event.issue.title, '[BUG]')
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['bug', 'needs-triage']
            });

  notify-license-inquiries:
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && contains(github.event.issue.labels.*.name, 'license')
    steps:
      - name: Notify team of license inquiry
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const comment = `Thank you for your interest in Transparency! 🎉
            
            We've received your licensing inquiry and will review it within 1-2 business days. 
            
            In the meantime, you can:
            - Check out our [documentation](https://github.com/transparency-platform/transparency/blob/main/README.md)
            - Try the free version to evaluate the platform
            - Join our [community discussions](https://github.com/transparency-platform/transparency-community/discussions)
            
            For urgent inquiries, you can also reach out directly via email.
            
            Best regards,
                          The Transparency Team`;
            
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: comment
            });

  community-metrics:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate community metrics
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            
            // Get issues and PRs from last 30 days
            const thirtyDaysAgo = new Date();
            thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);
            
            const issues = await github.rest.issues.listForRepo({
              owner,
              repo,
              state: 'all',
              since: thirtyDaysAgo.toISOString(),
              per_page: 100
            });
            
            const licenseInquiries = issues.data.filter(issue => 
              issue.labels.some(label => label.name === 'license')
            );
            
            const featureRequests = issues.data.filter(issue => 
              issue.labels.some(label => label.name === 'enhancement')
            );
            
            const bugReports = issues.data.filter(issue => 
              issue.labels.some(label => label.name === 'bug')
            );
            
            console.log(`Community Metrics (Last 30 days):
            - Total Issues: ${issues.data.length}
            - License Inquiries: ${licenseInquiries.length}
            - Feature Requests: ${featureRequests.length}
            - Bug Reports: ${bugReports.length}
            `);

  stale-issue-management:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Mark stale issues
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had 
            recent activity. It will be closed if no further activity occurs. 
            
            If this is still relevant, please comment to keep it open.
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had 
            recent activity. It will be closed if no further activity occurs.
            
            If this is still relevant, please comment to keep it open.
          close-issue-message: |
            This issue has been automatically closed due to inactivity. 
            
            If you believe this was closed in error, please reopen it or create a new issue.
          close-pr-message: |
            This pull request has been automatically closed due to inactivity.
            
            If you believe this was closed in error, please reopen it.
          days-before-stale: 60
          days-before-close: 7
          exempt-issue-labels: 'license,business,pinned,security'
          exempt-pr-labels: 'pinned,security'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale' 